This is example of 1D - Series

In [18]:
import pandas as pd
data = [10, 20, 30, 40, 50]
s = pd.Series(data)
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

This is example of 2D - DataFrame

In [19]:
import pandas as pd
student_data = {
    "Name": ["Vishal","Mansi","Avishek"],
    "Course": ["Data Science", "Web Development", "Machine Learning"],
    "Address": ["Delhi", "Mumbai", "Bangalore"]
}
df = pd.DataFrame(student_data)
print(df)

      Name            Course    Address
0   Vishal      Data Science      Delhi
1    Mansi   Web Development     Mumbai
2  Avishek  Machine Learning  Bangalore

In [20]:
import pandas as pd
df = pd.read_csv("D:\\sandbox\\Python-Agentic-AI-Course\\cars.csv")
print(df)

  Toyota    Camry  2020  Sedan
0  Honda    Civic  2019  Sedan
1   Ford  Mustang  2021  Coupe
2  Tesla  Model 3  2022  Sedan

In [21]:
import pandas as pd
import yfinance as yf
ticker="TCS.NS"
df = yf.download(ticker, start="2025-01-01", end="2026-05-09")
# Display the first few rows of the DataFrame

[*********************100%***********************]  1 of 1 completed

In [22]:
#print the first few rows of the DataFrame
df.head()

Price             Close         High          Low         Open   Volume
Ticker           TCS.NS       TCS.NS       TCS.NS       TCS.NS   TCS.NS
Date
2025-01-01  3903.252441  3923.706021  3877.625683  3886.120355   763161
2025-01-02  3963.332764  3970.213962  3888.541445  3910.418724  1720835
2025-01-03  3891.340820  3967.319010  3884.127566  3967.319010  1791953
2025-01-06  3886.690186  3938.560085  3859.544955  3896.656058  2085593
2025-01-07  3823.383301  3929.733444  3807.485361  3905.625616  2669054

In [23]:
# print the last few rows of the DataFrame
df.tail()

Price             Close         High          Low         Open   Volume
Ticker           TCS.NS       TCS.NS       TCS.NS       TCS.NS   TCS.NS
Date
2026-05-04  2431.300049  2498.300049  2425.000000  2494.000000  2632358
2026-05-05  2427.300049  2460.399902  2412.199951  2430.000000  3385720
2026-05-06  2435.399902  2471.000000  2406.500000  2441.899902  3147628
2026-05-07  2401.399902  2439.699951  2398.000000  2438.199951  5829594
2026-05-08  2394.399902  2407.000000  2375.100098  2398.000000  3792199

In [25]:
df.to_csv("D:\\sandbox\\Python-Agentic-AI-Course\\Day10\\tcs_stock_data.csv", index=False)

In [26]:
# stastical summary of the DataFrame
df.describe()

Price         Close         High          Low         Open        Volume
Ticker       TCS.NS       TCS.NS       TCS.NS       TCS.NS        TCS.NS
count    335.000000   335.000000   335.000000   335.000000  3.350000e+02
mean    3147.138211  3177.724752  3121.658569  3152.144622  2.990708e+06
std      400.859519   403.794498   398.601807   401.499131  1.586535e+06
min     2356.000000  2398.000000  2346.199951  2365.000000  0.000000e+00
25%     2962.520264  2988.082808  2943.004212  2967.827909  2.024766e+06
50%     3140.189941  3168.596349  3121.136422  3145.812649  2.670720e+06
75%     3360.526245  3391.106182  3338.259143  3366.489495  3.491448e+06
max     4072.814697  4103.044602  4012.354888  4083.159780  1.116874e+07

In [ ]:
df[["Close","Open","Volume"]]

Price             Close         Open   Volume
Ticker           TCS.NS       TCS.NS   TCS.NS
Date
2025-01-01  3903.252441  3886.120355   763161
2025-01-02  3963.332764  3910.418724  1720835
2025-01-03  3891.340820  3967.319010  1791953
2025-01-06  3886.690186  3896.656058  2085593
2025-01-07  3823.383301  3905.625616  2669054
...                 ...          ...      ...
2025-05-22  3360.851562  3378.250276  2034383
2025-05-23  3397.195801  3360.851725  1274331
2025-05-26  3419.137451  3403.381901   967470
2025-05-27  3381.826904  3414.014575  2467680
2025-05-28  3380.860107  3402.415228  1222933

[100 rows x 3 columns]